### PR TITLE
Automated cherry pick of #675: Stricter dependency/security review & update go version
#720: update the go version to 1.21.3

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #675 #720 on release-1.23.

#675: Stricter dependency/security review & update go version
#720: update the go version to 1.21.3

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Looks like some other dependency updates are needed for a clean bill of health, do you want to move that + the govulncheck workflow to a separate PR?

**Comment by hakman** [comment]
> Looks like some other dependency updates are needed for a clean bill of health, do you want to move that + the govulncheck workflow to a separate PR?

Let me give it a try

**Comment by cartermckinnon** [comment]
thanks @hakman !

/lgtm
/approve

**Pull request merged**
