### PR TITLE
Vendor aws

### PR DESCRIPTION
**Pull request by sargun**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
It makes it so all the code is in one place.

**Which issue(s) this PR fixes**:
This addresses some of the concerns in https://github.com/kubernetes/cloud-provider-aws/issues/42#issuecomment-635617333. 

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by nckturner** [comment]
I appreciate this, but we're not ready to move the cloud provider code from legacy-cloud-providers quite yet.  When we do, we will stop accepting commits there, but we only want one source of truth for now.

**Comment by sargun** [comment]
@nckturner I'm curious why, and when? Depending on the answer to this, we will consider forking, or waiting for the change. Right now, it's fairly difficult for us to manage the current process.

**Comment by nckturner** [comment]
@sargun That's fair.  ASAP, ideally.  Maybe we can get your changes merged upstream into k/k, or look into @andrewsykim's V2 proposal.  Thirdly, you're right, we could copy the code over here.  I'd like to have the timeline concrete if we do that, and know exactly when we are deprecating the in-tree provider.  I'll bring it up tomorrow in the provider-aws meeting.

**Pull request closed without merging**
