### PR TITLE
Bump Chart and appVersion

### PR DESCRIPTION
**Pull request by STASiAN**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This commit actualize latest release version in helm chart

### CODE REVIEW

**Comment by STASiAN** [comment]
Hi Guys! Please approve...
@justinsb @nckturner @hakman

**Review by olemarkus — APPROVED** [review]

**Comment by STASiAN** [comment]
Hi anything else is needed for merge?

**Comment by STASiAN** [comment]
Hi guys! Anything else is needed for merge?

**Pull request merged**
