### PR TITLE
Replace book homepage with README

### PR DESCRIPTION
**Pull request by ayberk**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Moved README to `/docs` and set the `/docs` folder as the `docs_dir` so now README.md serves as the home page for the mkdocs. 

Tested on my fork.

```release-note
NONE
```

### CODE REVIEW

**Comment by nckturner** [comment]
Did the assets need to be included in the PR?

**Review by nckturner — APPROVED** [review]

**Comment by nckturner** [comment]
To answer my previous question, looks like not.  Another question -- should we 1. remove netlify, or 2. update it?  cc @andrewsykim.  I'm not sure I understand what benefit it provides.

**Comment by ayberk** [comment]
Well, it's hosted on Netlify and our subproject DNS points to that deployment(https://cloud-provider-aws.sigs.k8s.io/). I think I should be able to modify it to work. Let me try.

**Comment by nckturner** [comment]
Oh got it.  Yeah we should try to update it.

**Comment by ayberk** [comment]
/unhold

@nckturner Should be working now. `deploy/netlify` correctly renders the docs. I think it deploys to the actual site when we merge to master.

**Comment by nckturner** [comment]
Thanks
/lgtm

**Pull request merged**
