### PR TITLE
Bump go mod version

### PR DESCRIPTION
**Pull request by ndbaker1**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Addresses govulncheck vulnerabilities with go version and project dependencies

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by echyam** [comment]
I wonder if there is a plan to add a dependabot config like in the azure repo to automatically bump dependencies?

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/.github/dependabot.yml

**Comment by kmala** [comment]
> I wonder if there is a plan to add a dependabot config like in the azure repo to automatically bump dependencies?
> 
> https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/.github/dependabot.yml

yes, there is dependabot https://github.com/kubernetes/cloud-provider-aws/blob/master/.github/dependabot.yaml but it needs to be expanded to update the go version

**Pull request merged**
