### PR TITLE
Release 1.27.3

### PR DESCRIPTION
**Pull request by cartermckinnon**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by YanzhaoLi** [comment]
Can this be released now?  May I know what is blocking this release?

**Comment by cartermckinnon** [comment]
Hm I didn't notice the version.txt file on release-1.27 was never updated when 1.27.2 was cut. That release was done on the master branch (incorrectly) IIRC.

Not sure if we should cherry-pick the release commit onto release-1.27 or just change this PR to 1.27.3, WDYT @hakman?

**Comment by hakman** [comment]
Let's go with 1.27.3. Thanks!

**Pull request merged**
