### PR TITLE
Update the docs

### PR DESCRIPTION
**Pull request by ayberk**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Follow up to #165

```release-note
NONE
```

### CODE REVIEW

**Comment by nckturner** [comment]
Hm might need to figure out how to prevent the tests from running on PRs to gh-pages

**Comment by nckturner** [comment]
Merged because tests don't apply to gh-pages branch.

**Comment by ayberk** [comment]
Yeah we did it for the ebs driver. Will send a PR today.

**Pull request merged**
