### PR TITLE
Allows user to specify imagepullsecret

### PR DESCRIPTION
**Pull request by apt-x4869**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
Requirement is to specify credentials for pulling image from private registry. 

**Which issue(s) this PR fixes**:
Allows user to specify imagepullsecret
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

release-note:
```release-note
Allows user to specify imagepullsecret
```

### CODE REVIEW

**Comment by kmala** [comment]
the helm charts are planned to be deleted and is discussed here https://github.com/kubernetes/cloud-provider-aws/issues/933

**Comment by cartermckinnon** [comment]
/hold

@apt-x4869 you'll need to sign the CLA before we can proceed.

**Comment by apt-x4869** [comment]
> /hold
> 
> @apt-x4869 you'll need to sign the CLA before we can proceed.

Signed

**Pull request closed without merging**
