### PR TITLE
Explain short tag with comment

### PR DESCRIPTION
**Pull request by hakman**
Fixes a nit noticed during #352 code review.

Ref: https://github.com/kubernetes/cloud-provider-aws/pull/352#discussion_r869192683

/cc @justinsb @nckturner

### CODE REVIEW

**Review by rifelpet — COMMENTED** [review]
/lgtm

**Comment by hakman** [comment]
@nckturner We tested this release with kOps and seems to work fine, so #353 could also be merged to fix the 1.23 branch.

**Pull request merged**
