### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manvindar**
Fixed spelling mistake
/kind documentation

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by leakingtapan** [comment]
Hey @manvindar thx for the pr. Please sign CLA to get the pr merged

**Comment by nckturner** [comment]
@manvindar please sign CLA to get this merged, and add NONE to release note.

**Pull request closed without merging**
