### PR TITLE
Add template annotations to daemonset

### PR DESCRIPTION
**Pull request by kkonnov**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Ability to specify pod annotations in templates.

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by kkonnov** [comment]
@hakman @jaypipes Hi.
Please tell me if I need to take additional steps to make my PR merged.
I've already fix easyCLA, but can't see any actions here.
Thank you in advance.

**Comment by cartermckinnon** [comment]
Looks reasonable.

/ok-to-test
/check-cla

**Comment by cartermckinnon** [comment]
@kkonnov you'll need to amend your commit and correct the email address (or add that email to your GitHub profile) to fix the CLA check.

**Comment by olemarkus** [comment]
This needs release notes.

**Comment by kkonnov** [comment]
Guys:

- I've changed email. 
- Signed CLA again with the new correct email. 
- run /check-cla /easy-cla

but faced the same issue. Please help me. 
What am I doing wrong?

**Comment by hakman** [comment]
@kkonnov We are not able to help here. Please create a support ticket as described in the above comment: https://github.com/kubernetes/cloud-provider-aws/pull/619#issuecomment-1588710259.
> * ❌ The email address for the commit ([69c16e8](https://github.com/kubernetes/cloud-provider-aws/commit/69c16e8aeb2d3c02da6d86341974d7874c7394a5)) is not linked to the GitHub account, preventing the EasyCLA check. Consult [this Help Article](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit's email address, add .patch at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

**Comment by kkonnov** [comment]
I got tired of fighting this MR and created a new one. https://github.com/kubernetes/cloud-provider-aws/pull/636
There CLA - went through successfully. This MR will be closed. Thanks for your help.

**Pull request closed without merging**
