### PR TITLE
Merge legacy provider

### PR DESCRIPTION
**Pull request by nckturner**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This copies the v1 provider to the local v1 directory.  This merge needs to be coordinated with an effort to stop accepting features into k/k (legacy-cloud-providers).

I was working off https://github.com/kubernetes/cloud-provider-aws/pull/151 (so those commits show up here too) as I am expecting us to get that in first, but I can separate this if for some reason we want this to merge first.

**Does this PR introduce a user-facing change?**:

```release-note
The V1 AWS provider has been rehomed from `legacy-cloud-providers` to `cloud-provider-aws/pkg/providers/v1`
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
/hold 

Just putting a hold on this on @nicolehanjing 's PR is merged

**Comment by nicolehanjing** [comment]
> /hold
> 
> Just putting a hold on this until @nicolehanjing 's PR is merged

@andrewsykim FYI my PR has merged

**Comment by nckturner** [comment]
Ok I will rebase this

**Pull request merged**
