### PR TITLE
Release 1.26.0-rc.1

### PR DESCRIPTION
**Pull request by olemarkus**
Release 1.26-rc.1

/release-notes-none

### CODE REVIEW

**Comment by hakman** [comment]
@olemarkus Are you sure you don't want a beta for now?

**Comment by olemarkus** [comment]
Uh I just followed the convention of the upstream libs. That's the big change here anyway. We can call it beta if that matters, but I imagine the only change before the GA release would be to bump the k8s deps to GA.

**Review by hakman — APPROVED** [review]

**Pull request merged**
