### PR TITLE
Bump aws-sdk-go version to 1.44.145

### PR DESCRIPTION
**Pull request by xdu31**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Bump aws-sdk-go version to 1.44.145

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update aws-sdk-go to 1.44.145
```

### CODE REVIEW

**Comment by wongma7** [comment]
could you fill in the release note under "Does this PR introduce a user-facing change?:" something simple like

Updates aws-sdk-go to v1.42.20
https://github.com/kubernetes/cloud-provider-aws/pull/292

**Comment by wongma7** [comment]
/release-note-edit ```release-note Update aws-sdk-go to 1.44.145```

**Comment by wongma7** [comment]
nodes not joining, I am not sure the issue is specific to the PR, https://github.com/kubernetes/cloud-provider-aws/pull/530#issuecomment-1326636051 is also failing.

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cloud-provider-aws-e2e

/retest

**Comment by hakman** [comment]
After merging https://github.com/kubernetes/cloud-provider-aws/pull/532, the nodes are again joining the cluster.
/lgtm

**Pull request merged**
