### PR TITLE
Update README with latest releases

### PR DESCRIPTION
**Pull request by HusainZafar**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This PR updates README with the latest cloud-provider-aws release tags for k8s versions 1.20-1.24 and adds the latest release tags for versions 1.25-1.26

**Which issue(s) this PR fixes**:
Fixes # None

**Special notes for your reviewer**: NONE

**Does this PR introduce a user-facing change?**: NONE

### CODE REVIEW

**Comment by HusainZafar** [comment]
I have requested CLA Authorization as a Corporate Contributor and the approval is pending from the organization

**Review by kishorj — APPROVED** [review]

**Pull request merged**
