### PR TITLE
Removed emeritus reviewers from SECURITY_CONTACTS

### PR DESCRIPTION
**Pull request by micahhausler**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

cc @jaypipes @dims can you both +1?

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by orsenthil — APPROVED** [review]

**Comment by dims** [comment]
+1 from me!

**Review by hakman — APPROVED** [review]

**Comment by micahhausler** [comment]
Confirmed from @jaypipes in Slack he's good to remove.

/unhold

**Comment by cartermckinnon** [comment]
@micahhausler I think you'll need to rebase to fix the dependency checks

**Comment by micahhausler** [comment]
@cartermckinnon rebased, thanks!

**Pull request merged**
