### PR TITLE
Release 1.27.7

### PR DESCRIPTION
**Pull request by javanthropus**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by javanthropus** [comment]
@cartermckinnon, when are new container images published?  The latest available version for 1.27 still seems to be v1.27.6 according to registry.k8s.io.

**Comment by cartermckinnon** [comment]
We have to promote the images from the staging repo, will get that done shortly

**Pull request merged**
