### PR TITLE
update klog library from 2.4.0 to 2.5.0

### PR DESCRIPTION
**Pull request by dineshkumar181094**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
/kind feature

**What this PR does / why we need it**:
* updates klog library from 2.4.0 to 2.5.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nckturner** [comment]
@dineshkumar181094 can you rebase?

**Comment by dineshkumar181094** [comment]
@andrewsykim  rebase done.
can you test it again.

**Comment by dineshkumar181094** [comment]
/assign @andrewsykim 
I have checked the logs of jobs.
The failure is due to merge conflicts, I have fixed that.
```CONFLICT (content): Merge conflict in go.mod
Automatic merge failed; fix conflicts and then commit the result.
# Error: exit status 1```

**Review by nckturner — APPROVED** [review]

**Pull request merged**
