### PR TITLE
Fix Dockerfile to add files in /pkg folder

### PR DESCRIPTION
**Pull request by nicolehanjing**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fixes Dockerfile to add files in /pkg folder

**Which issue(s) this PR fixes**:

Fixes Dockerfile

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
@nicolehanjing , would be worth filing a request to join the kubernetes-sigs org via https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

Thanks @nicolehanjing

**Comment by andrewsykim** [comment]
I also filed https://github.com/kubernetes/cloud-provider-aws/issues/135 as a follow-up, we should be compiling aws-cloud-controller-manager as part of CI

**Comment by nicolehanjing** [comment]
> @nicolehanjing , would be worth filing a request to join the kubernetes-sigs org via https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E so don't need to wait for ok-to-test bits.
> 
> Need one non-VMware sponsor

gotcha! Thanks for letting me know

**Pull request merged**
