### PR TITLE
Update kOps command for creating clusters

### PR DESCRIPTION
**Pull request by kmala**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation

 /kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:
This is cherry-pick of https://github.com/kubernetes/cloud-provider-aws/pull/553
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by kishorj — APPROVED** [review]

**Comment by dims** [comment]
/approve
/lgtm

(unfortunatly i don't have karma for approval)

**Pull request merged**
