### PR TITLE
Bump the go version to v1.15 latest

### PR DESCRIPTION
**Pull request by nicolehanjing**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
bump the go version to v1.15 latest

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Bump the go version to v1.15 latest
```

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
We also need to bump the golang image in the Dockerfile:

https://github.com/kubernetes/cloud-provider-aws/blob/9a026c69043aaee536bdf1bfc43e882749513fd6/Dockerfile#L17

**Comment by nicolehanjing** [comment]
> We also need to bump the golang image in the Dockerfile:
> 
> https://github.com/kubernetes/cloud-provider-aws/blob/9a026c69043aaee536bdf1bfc43e882749513fd6/Dockerfile#L17

updated! :)

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

Thanks @nicolehanjing!

**Pull request merged**
