### PR TITLE
Migrate k8s e2e to Ginkgo 2.0

### PR DESCRIPTION
**Pull request by hakman**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Get e2e test feedback from latest stable k8s version.

**Which issue(s) this PR fixes**:

n/a

**Special notes for your reviewer**:
n/a

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]
Thanks a lot! Really wanted to get to this myself.

**Comment by olemarkus** [comment]
/hold

You maybe want to squash?

**Comment by hakman** [comment]
Thanks @olemarkus. I think is as far as I can get it for now.
In the future, it still need some way export the artifacts to get the list of tests in the summary.

**Pull request merged**
