### PR TITLE
Adding snapshot ID option for EBS volume creation

### PR DESCRIPTION
**Pull request by zacharya**
```release-note
NONE
```

Enhancement per #28

### CODE REVIEW

**Comment by jsafrane** [comment]
IMO, this should belong to CSI AWS driver in https://github.com/kubernetes-sigs/aws-ebs-csi-driver. It's getting snapshot support right now.

**Comment by leakingtapan** [comment]
@zacharya we are working on adding snapshot for EBS csi driver where all the new features will be developed there. If you are interested in contributing, please let me know.

**Comment by zacharya** [comment]
@leakingtapan I'd love to contribute

**Comment by zacharya** [comment]
Closing as noted above, this will be handled by the EBS CSI driver

**Pull request closed without merging**
