### PR TITLE
Update upstream dependencies to 1.31.0

### PR DESCRIPTION
**Pull request by shizuchanw**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Version Release following upstream v1.31.0 release
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by cartermckinnon** [comment]
@shizuchanw I think we need to do separate PR's for the `version.txt` bump and all the dependencies changes. Let's land the dependency changes first to make sure we're cutting a stable release

**Comment by shizuchanw** [comment]
> @shizuchanw I think we need to do separate PR's for the `version.txt` bump and all the dependencies changes. Let's land the dependency changes first so it flows into CI and we can make sure we're cutting a stable release

Thank you!! Updating that right now

**Comment by hakuna-matatah** [comment]
Could you please try with this KOPS_VERSION_MARKER `https://storage.googleapis.com/k8s-staging-kops/kops/releases/markers/master/latest-ci.txt`  ?

**Comment by hakuna-matatah** [comment]
> Could you please try with this KOPS_VERSION_MARKER `https://storage.googleapis.com/k8s-staging-kops/kops/releases/markers/master/latest-ci.txt` ?

Looks like it worked @cartermckinnon @shizuchanw

**Pull request merged**
