### PR TITLE
Fix Daemonset Extra Args Helm Template

### LINKED ISSUE #235: Helm Template Doesnt Use extraArgs to daemonset
**What happened**:

Currently, the helm template for the daemonset does not utilize the `extraArgs` key at all. It is intended
to allow users to specify additional arguments to the daemonset.

**What you expected to happen**:

Values in the `extraArgs` key should be provided to the daemonset as arguments.

**How to reproduce it (as minimally and precisely as possible)**:

Look at the helm template for daemonset.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by jtcarnes**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Fixes issue with helm chart

**Which issue(s) this PR fixes**:

Fixes #235 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fixes arguments for helm daemonset template
```

### CODE REVIEW

**Comment by jtcarnes** [comment]
cla signed. If you could check again that would be helpful

**Comment by jtcarnes** [comment]
Perhaps we want to change extraArgs to flags and have all flags under it instead. Currently, you cant change the verbosity level. Have that and cloud provider be keys under args

**Comment by nckturner** [comment]
I agree with your idea to use flags instead of extraArgs, would you like to add that to this PR?

**Comment by romanchi12** [comment]
@nckturner @jtcarnes any updates here? This issue is blocking upgrading k8s from 1.20 to 1.21.

**Pull request closed without merging**
