### PR TITLE
Trim date prefix from tag in GCB image build

### LINKED ISSUE #339: panic: version string "v20220409-v1.23.0" doesn't match expected regular expression
**What happened**:
Tests fail because `aws-cloud-controller-manager` fail to start:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/13452/pull-kops-e2e-cni-cilium-ipv6/1516070708126420992
```
==== START logs for container aws-cloud-controller-manager of pod kube-system/aws-cloud-controller-manager-94ngm ====
panic: version string "v20220409-v1.23.0" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion({{0x0, 0x0}, {0x0, 0x0}, {0x29703c0, 0x11}, {0x254765f, 0xb}, {0x0, 0x0}, ...})
	k8s.io/component-base@v0.23.5/metrics/version_parser.go:47 +0x27e
k8s.io/component-base/metrics.newKubeRegistry({{0x0, 0x0}, {0x0, 0x0}, {0x29703c0, 0x11}, {0x254765f, 0xb}, {0x0, 0x0}, ...})
	k8s.io/component-base@v0.23.5/metrics/registry.go:320 +0x118
k8s.io/component-base/metrics.NewKubeRegistry()
	k8s.io/component-base@v0.23.5/metrics/registry.go:335 +0x78
k8s.io/component-base/metrics/legacyregistry.init()
	k8s.io/component-base@v0.23.5/metrics/legacyregistry/registry.go:29 +0x1d
==== END logs for container aws-cloud-controller-manager of pod kube-system/aws-cloud-controller-manager-94ngm ====
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Try to start `aws-cloud-controller-manager` using the latest stable image: `registry.k8s.io/provider-aws/cloud-controller-manager:v1.23.0`.

**Anything else we need to know?**:
Guess it's related to: https://github.com/kubernetes/cloud-provider-aws/pull/317.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.23.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`):
- Install tools: kOps
- Others: n/a

/kind bug

### PR DESCRIPTION
**Pull request by rifelpet**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
The image pushing setup in test-infra defines `_GIT_TAG` with a `vYYYYMMDD` prefix to `git describe`.

This format isn't allowed by k8s.io/component-base panicking on startup.

By trimming the date prefix from the tag, image builds will only contain the `git describe` output, matching the binaries built from the Makefile

**Which issue(s) this PR fixes**: 

Fixes #339

**Special notes for your reviewer**:

I copied this solution from another project's build process that also utilizes GCB and k8s.io/component-base:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/1c90b0d319f33c7a33d9456ba412be0b6ffb61bc/Makefile#L31-L36

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]
/lgtm

**Comment by nckturner** [comment]
/lgtm
/approve

Thanks @rifelpet

**Comment by hakman** [comment]
@nckturner Could you cherry-pick this to 1.23 and release both 1.23 and 1.24 with this fix? Thanks!

**Pull request merged**
