### PR TITLE
A missing item

### PR DESCRIPTION
**Pull request by oguzhanun**
I hope this will save other people's time...

**What type of PR is this?**

> /kind documentation

**What this PR does / why we need it**:

It improves the quality of the documentation.

**Which issue(s) this PR fixes**:

Fixes #
A to-do list to be able to run AWS cloud-controller-manager on a k8s cluster.

**Special notes for your reviewer**:
Thanks for your time...

**Does this PR introduce a user-facing change?**:

NONE
```release-note
NONE
```

### CODE REVIEW

**Comment by ayberk** [comment]
Thanks @oguzhanun. Before we can merge your contribution, we'll need you to sign the CLA. It looks like your commit is correctly associated with your github account, so you just need to sign the CLA using an email you use for you Github account. You can see all email addresses associated with your Github account in your account settings.

https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

**Comment by oguzhanun** [comment]
Hi @ayberk, thanks a lot for your help. I have completed the signing procedures.

**Comment by nckturner** [comment]
This is helpful, but probably not enough information.  In fact, I think we should merge this and then add more context.  I'll create an issue after this merges.

**Review by nckturner — APPROVED** [review]

**Pull request merged**
