### PR TITLE
Bump K8s libs to 0.25.3

### PR DESCRIPTION
**Pull request by lobziik**
/kind bug
/kind cleanup

**What this PR does / why we need it**:
Bug described in https://github.com/kubernetes/kubernetes/issues/112793  was introduced in released versions of `k8s.io/cloud-provider`, namely in v0.25.(0, 1, 2). This was fixed in the most recent `k8s.io/cloud-provider` version `v0.25.3`. This PR bumps k8s libs to bring this fix into cloud-provider-aws.

Also, this patch bumps k8s libs version for the e2e test suite.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by olemarkus** [comment]
Doesn't look like the version bumps pass tests just like that, unfortunately. It errors out in a panic.

**Comment by lobziik** [comment]
@olemarkus I rolled back bump for e2e suite, `k8s.io/kubernetes/test/e2e/framework` introduces dependency on ginkgo v2 which caused this panic as far as i understand.

I suggest to address dependency bump for e2e suite in follow-up PR, this shouldn't affect this test essence i think.

**Review by olemarkus — APPROVED** [review]
I thought we already bumped to ginkgo v2. I've seen this error before when one used mixed versions though. We'll have a look in a followup PR.

**Pull request merged**
