### PR TITLE
Reflect community ownership in default image name

### PR DESCRIPTION
**Pull request by dims**
Same change that we did earlier here:
https://github.com/kubernetes/cloud-provider-aws/commit/2346f203ce325913ef8ed8d19b6283495ae43749#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R23

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
I am still working on the CI jobs :) so merging this by hand.

**Comment by hakman** [comment]
/approve
😄

**Pull request merged**
