### PR TITLE
Automated cherry pick of #502: single update to node cache

### PR DESCRIPTION
**Pull request by kon-angelo**
Cherry pick of https://github.com/kubernetes/cloud-provider-aws/pull/502 on release-1.26.

https://github.com/kubernetes/cloud-provider-aws/pull/502: single update to node cache

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by kon-angelo** [comment]
cc: @dims @olemarkus

**Comment by hakman** [comment]
@dims Any objection to merging this?
/lgtm

**Pull request merged**
