### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by nckturner**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>

/kind documentation

**What this PR does / why we need it**:
* Update changelog.py to support PRs without merge commits
* Add v1.22.0 to CHANGELOG.md

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
could we make master branch source of truth for CHANGELOGs? how k/k does it is they have master branch changelogs https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG  and then a bot updates the per-branch changelogs  https://github.com/kubernetes/kubernetes/blob/release-1.22/CHANGELOG/CHANGELOG-1.22.md

We don't have a bot but I don't think it is super necessary to have useful per-branch changelogs anyway

**Comment by wongma7** [comment]
Wait no, this PR is already targeting master branch so yes master branch is already source of truth. MY B ignore prev comment -_-

**Comment by nckturner** [comment]
> could we make master branch source of truth for CHANGELOGs?

That's what I was doing, what do you mean?

**Pull request merged**
