### PR TITLE
Allow user to specify Registry Pull Secret

### PR DESCRIPTION
**Pull request by apt-x4869**
**What type of PR is this?** /kind feature

**What this PR does / why we need it**:
Requirement is to specify credentials for pulling image from private registry. 

**Which issue(s) this PR fixes**:
Allows user to specify imagepullsecret
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

release-note:
```release-note
Allow user to specify imagePullSecrets 
```

### CODE REVIEW

**Comment by apt-x4869** [comment]
@cartermckinnon @dims ,
Could you review ?

**Comment by dims** [comment]
@apt-x4869 dunno which way we will go https://github.com/kubernetes/cloud-provider-aws/issues/933 

Do you mind adding what your use case is in that issue?

**Comment by apt-x4869** [comment]
> @apt-x4869 dunno which way we will go #933
> 
> Do you mind adding what your use case is in that issue?

Added use case.

**Comment by apt-x4869** [comment]
@cartermckinnon @dims ,
Could you review ?

**Comment by apt-x4869** [comment]
Hello
Any remarks?

**Comment by apt-x4869** [comment]
Hello @cartermckinnon @dims 

Could I have a review ?

Thanks,
Aman

**Comment by apt-x4869** [comment]
@cartermckinnon @dims ,
Could you please review ?
Sadly, it has been two months now for this simple change.

**Comment by kmala** [comment]
since there are use cases mentioned in #933 , we can pick the new changes to the helm template for now. Sorry for the delay @apt-x4869 
/ok-to-test

**Comment by apt-x4869** [comment]
@kmala 
Needs approved, lgtm labels.

**Pull request merged**
