### PR TITLE
docs(footer): Add trademark disclaimer

### LINKED ISSUE #837: Website does not have the correct trademark disclaimer
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

### PR DESCRIPTION
**Pull request by mariasalcedo**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Adds correct trademark disclaimer, as part of our ongoing effort to https://github.com/cncf/techdocs/issues/198

**Which issue(s) this PR fixes**:
Fixes #837

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Thank you @mariasalcedo !

/lgtm
/approve

**Comment by mariasalcedo** [comment]
@cartermckinnon it seems like test pipeline failed due to resources not being found. Please check.

**Comment by cartermckinnon** [comment]
Not related to this change, going ahead.

**Pull request merged**
