### PR TITLE
Fix issue with flag causing test failures

### PR DESCRIPTION
**Pull request by saurav-agarwalla**
`make test` is now successful (it was failing prior to this change).

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**: Fix issue with flag causing test failures

**Which issue(s) this PR fixes**: N/A

**Special notes for your reviewer**: NONE

**Does this PR introduce a user-facing change?**: 
```release-note
NONE
```

### CODE REVIEW

**Comment by saurav-agarwalla** [comment]
Fixes failing test in https://github.com/kubernetes/cloud-provider-aws/pull/363#issuecomment-1124974059.

**Comment by nckturner** [comment]
Needs e2e test directory, hack/e2e scripts and Makefile targets.

**Comment by saurav-agarwalla** [comment]
Closing in favor of https://github.com/kubernetes/cloud-provider-aws/pull/370 where I added the E2E tests as well.

**Pull request closed without merging**
